#!/usr/bin/env bash

tabbed=( 1:Web )

for w in $tabbed; do
	i3-msg "workspace $w; layout stacked"
done

i3-msg 'workspace 5:Chatten; append_layout /home/tuxinaut/.i3/workspace_chatten.json'
i3-msg "workspace 1:Web"
